[project]
name = "tsp-solver-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ortools>=9.12.4544",
    "python-tsp>=0.5.0",
    "pyvrp>=0.10.1",
    "ruff>=0.11.2",
]
